// =======================================================================
//  PatchFileData.cs — PatchFileList data model (Phase R4)
//
//  Source: _shared/DecompiledSource/KKUpdater/PatchFileList.cs (field layout)
//         _shared/DecompiledSource/KKUpdater/PatchFile.cs
//         _shared/DecompiledSource/KKUpdater/OptionalPatchFile.cs
//
//  Original namespace: KKUpdater
//  Format matches PatchFileList.json generated by BundleBuildPipeline.
// =======================================================================

using System;
using System.Collections.Generic;
using UnityEngine;

namespace KTO.Resource
{
    // Source: KKUpdater.PatchFile — { date, MD5, size, ver }
    [Serializable]
    public class PatchFile
    {
        public string date;
        public string MD5;
        public int size;
        public int ver;
    }

    // Source: KKUpdater.OptionalPatchFile extends PatchFile + priority
    [Serializable]
    public class OptionalPatchFile : PatchFile
    {
        public int priority;
    }

    // Source: KKUpdater.PatchFileList — { MainVersion, UpdateVersion, FileList, OptionalPatchFileList }
    [Serializable]
    public class PatchFileListData
    {
        public string MainVersion;
        public int UpdateVersion;
        public Dictionary<string, PatchFile> FileList;
        public Dictionary<string, OptionalPatchFile> OptionalPatchFileList;
        public bool isDone;

        public PatchFileListData()
        {
            FileList = new Dictionary<string, PatchFile>();
            OptionalPatchFileList = new Dictionary<string, OptionalPatchFile>();
        }

        // =================================================================
        //  isLegal — Check if this manifest is valid for the given version
        //
        //  Source: IL2CPP PatchFileList__isLegal (0x01ac7927)
        // =================================================================
        public bool IsLegal(string validVersion)
        {
            return !string.IsNullOrEmpty(MainVersion) &&
                   MainVersion == validVersion &&
                   FileList != null;
        }

        // =================================================================
        //  ParseFromJson — Deserialize from JSON string
        //
        //  Source: IL2CPP PatchFileList__Unmarshal (0x01ac7a3e)
        //    Uses MiniJSON.Deserialize internally (original).
        //    We use Unity's JsonUtility + manual dict parsing.
        // =================================================================
        public static PatchFileListData ParseFromJson(string json)
        {
            if (string.IsNullOrEmpty(json)) return null;

            try
            {
                // Unity's JsonUtility can't handle Dictionary, so parse manually
                var wrapper = JsonUtility.FromJson<PatchFileListJsonWrapper>(json);
                var result = new PatchFileListData
                {
                    MainVersion = wrapper.MainVersion,
                    UpdateVersion = wrapper.UpdateVersion,
                    isDone = true
                };

                // Parse FileList manually from JSON
                // The JSON is { "FileList": { "path": { "date":"...", "MD5":"...", "size":N, "ver":N } } }
                // Use simple JSON parsing since we control the format
                result.FileList = ParseFileListFromJson(json, "FileList");
                result.OptionalPatchFileList = ParseOptionalFromJson(json, "OptionalPatchFileList");

                return result;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[PatchFileListData] Failed to parse JSON: {ex.Message}");
                return null;
            }
        }

        // Simple JSON parser for FileList entries
        // This handles our known format without needing Newtonsoft/MiniJSON
        static Dictionary<string, PatchFile> ParseFileListFromJson(string json, string key)
        {
            var dict = new Dictionary<string, PatchFile>();

            // Find the "FileList": { section
            int keyIdx = json.IndexOf($"\"{key}\"");
            if (keyIdx < 0) return dict;

            int braceStart = json.IndexOf('{', keyIdx + key.Length + 3);
            if (braceStart < 0) return dict;

            // Find matching closing brace
            int depth = 1;
            int pos = braceStart + 1;
            while (pos < json.Length && depth > 0)
            {
                if (json[pos] == '{') depth++;
                else if (json[pos] == '}') depth--;
                if (depth > 0) pos++;
            }
            if (depth != 0) return dict;

            string section = json.Substring(braceStart + 1, pos - braceStart - 1);

            // Parse each entry: "path": { "date":"...", "MD5":"...", "size":N, "ver":N }
            int cursor = 0;
            while (cursor < section.Length)
            {
                // Find next quoted path
                int pathStart = section.IndexOf('"', cursor);
                if (pathStart < 0) break;
                int pathEnd = section.IndexOf('"', pathStart + 1);
                if (pathEnd < 0) break;

                string path = section.Substring(pathStart + 1, pathEnd - pathStart - 1);

                // Find the opening brace of the value object
                int valStart = section.IndexOf('{', pathEnd);
                if (valStart < 0) break;
                int valEnd = section.IndexOf('}', valStart);
                if (valEnd < 0) break;

                string valJson = section.Substring(valStart, valEnd - valStart + 1);
                cursor = valEnd + 1;

                // Parse the value
                var pf = JsonUtility.FromJson<PatchFile>(valJson);
                if (pf != null)
                    dict[path] = pf;
            }

            return dict;
        }

        static Dictionary<string, OptionalPatchFile> ParseOptionalFromJson(string json, string key)
        {
            var dict = new Dictionary<string, OptionalPatchFile>();

            int keyIdx = json.IndexOf($"\"{key}\"");
            if (keyIdx < 0) return dict;

            int braceStart = json.IndexOf('{', keyIdx + key.Length + 3);
            if (braceStart < 0) return dict;

            int depth = 1;
            int pos = braceStart + 1;
            while (pos < json.Length && depth > 0)
            {
                if (json[pos] == '{') depth++;
                else if (json[pos] == '}') depth--;
                if (depth > 0) pos++;
            }
            if (depth != 0) return dict;

            string section = json.Substring(braceStart + 1, pos - braceStart - 1);
            if (string.IsNullOrWhiteSpace(section)) return dict;

            int cursor = 0;
            while (cursor < section.Length)
            {
                int pathStart = section.IndexOf('"', cursor);
                if (pathStart < 0) break;
                int pathEnd = section.IndexOf('"', pathStart + 1);
                if (pathEnd < 0) break;

                string path = section.Substring(pathStart + 1, pathEnd - pathStart - 1);

                int valStart = section.IndexOf('{', pathEnd);
                if (valStart < 0) break;
                int valEnd = section.IndexOf('}', valStart);
                if (valEnd < 0) break;

                string valJson = section.Substring(valStart, valEnd - valStart + 1);
                cursor = valEnd + 1;

                var pf = JsonUtility.FromJson<OptionalPatchFile>(valJson);
                if (pf != null)
                    dict[path] = pf;
            }

            return dict;
        }

        // Helper for JsonUtility (top-level only — dicts parsed manually)
        [Serializable]
        class PatchFileListJsonWrapper
        {
            public string MainVersion;
            public int UpdateVersion;
        }
    }
}
